project:
  type: website
  output-dir: docs

website:
  title: "Adelaide Robinson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - hello.qmd
      - href: posts.qmd
        text: Blog Posts
format:
  html:
    theme:
      - mystyles.scss
    mainfont: nunitosans 
    toc: true

editor: visual

